name: Reddit News Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours

jobs:
  post-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download deduplication artifacts
        uses: actions/download-artifact@v4
        with:
          name: deduplication-files
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install praw feedparser requests beautifulsoup4

      - name: Run Reddit News Bot
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDITPASSWORD: ${{ secrets.REDDITPASSWORD }}
        run: python internationalbulletin.py

      - name: Upload deduplication artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deduplication-files
          path: |
            posted_urls.txt
            posted_titles.txt
            posted_content_hashes.txt
