name: International Bulletin Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Use Python 3.11 for compatibility

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 praw

      # Run the bot script
      - name: Run International Bulletin Bot
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDITPASSWORD: ${{ secrets.REDDITPASSWORD }}
        run: |
          python internationalbulletin.py
        continue-on-error: true  # Proceed to upload artifacts even if script fails

      # Upload logs and records as artifacts
      - name: Upload logs and records
        uses: actions/upload-artifact@v4
        with:
          name: bot-logs
          path: |
            bot.log
            posted_records.txt
            rejected_articles.txt
          retention-days: 7
        if: always()  # Upload artifacts even on failure

      # Notify on failure (optional, requires Slack setup)
      - name: Notify on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: 'bot-notifications'
          text: 'International Bulletin Bot failed on ${{ github.run_id }}! Check logs in GitHub Actions.'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
