name: UK Royal Family News to Reddit

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-royal-news-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: List files for debugging
        run: ls -al

      - name: Run the royal news bot
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDITPASSWORD: ${{ secrets.REDDITPASSWORD }}
        run: python ukroyals.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add posted_urls.txt run_log_*.txt
          git commit -m "Update posted_urls.txt and run log" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
